### ISSUE TITLE
PFD.py only accessible from localhost

### ISSUE THREAD

**Issue by AndKe** [dddomodossola/PFD#1]
I've modified PFD.py with a port address to ensure same port:

start(Application, multiple_instance=False, start_browser=True, debug=False, port=8081)

running one .py at a time:
when I run PFD.py, it is only accessible from the host it runs on.
when I run basic_svg_example.py - it is accessible from any host on the LAN
(both use port 8081 - so it is not a firewall/network issue.

**Comment by dddomodossola** [comment]
@AndKe I pushed a change right now. Please give it a try. It was missing the start **address='0.0.0.0'**

**Comment by AndKe** [comment]
Thank you - that worked - so I got to test on google glass.
