### ISSUE TITLE
Two minor issues:

### ISSUE THREAD

**Issue by AndKe** [dddomodossola/PFD#10]
@dddomodossola 
1: VSI is inverted (a positive value makes the "needle" point down, it is supereasy to fix, I just thought you may want to have it fixed in master.)

2: when the compass do a roll-over from 359->0 or 0->359, there is a glitch in the graphics to the right only.
I tested using this code:
```
        yaw=200
        while self.thread_alive_flag:
            #calculations
            yaw=yaw-3
            if yaw < 0:
                yaw=359
```

This is how it looks:
![Screenshot from 2021-03-15 22-04-25](https://user-images.githubusercontent.com/1468842/111221748-2f21ac00-85db-11eb-910b-0a8dcbae788b.png)

The other simplifications are just my attempt to quantify performance hit by the object count. :)

**Comment by dddomodossola** [comment]
@AndKe I will fix these things tomorrow evening ;-)
however I can't see the compass problem in your image, I will try the code you provided

**Comment by AndKe** [comment]
maybe it happens first after one turn? - I'll provide a full test scenario if needed, with code and video, so do not spend too much time at trying to reproduce it.

Also, when you have time, please post a simple hint on how to change the font size of the text fields.

**Comment by dddomodossola** [comment]
@AndKe inverted labels of VSI. Changed font-size of text fields. Please look at the commit changes to see where to change font size for the text-fields.

**Comment by AndKe** [comment]
thank you . I am right on it..   Did you got notified about the margins?

**Comment by AndKe** [comment]
@dddomodossola  oops ! - there has been a misunderstanding about VSI.
The labels were fine, the "needle" should point up with a positive climb rate.
What I tried to ask for, was to make the VSI needle go "up" with positive numbers, not "down" (as it does)
The labels were fine. ("10" on the top , "-10" on the bottom)

**Comment by dddomodossola** [comment]
Fixed now ;-)

**Comment by AndKe** [comment]
Confirmed, Thank you

**Comment by AndKe** [comment]
And thank you for the speed-tape, it's great.
