### ISSUE TITLE
How to properly reset background color?

### ISSUE THREAD

**Issue by AndKe** [dddomodossola/PFD#11]
I do change some colors to make changes easy to spot:
```
        # Mode change awareness
        if time.time() - self.mode_change_time < 2:
            self.m.css_color = self.color_flipper[0]
            self.m.css_background_color = 'green'
        else:
            self.m.css_color = self.standard_label_color
            self.m.css_background_color = self.centering_container.css_background_color # 'black'
```

If the alarm is inactive, I reset the background to normal color scheme.
If the last line is 
```
self.m.css_background_color = 'black'
```
Then the alternating background caused by INOP flag does not affect that cell.
(seen in the video of the MODE field (m) from start to 30 seconds)

So I am using:
```
self.m.css_background_color = self.centering_container.css_background_color
```
And the result is seen (in "m" field)  from 30 to the end ... during INOP the m.css_background_color is not in sync of the rest of the INOP blinking, 

Please see https://drive.google.com/file/d/1nMiStngm0E6EW_86FB9Y1w5IKTvNrRIE/view?usp=sharing

How should I properly reset a background color?

**Comment by dddomodossola** [comment]
@AndKe you can do:

`del self.m.css_background_color`

**Comment by AndKe** [comment]
Thank you - it worked perfectly
