### ISSUE TITLE
Please place a GS (groundspeed) textbox

### ISSUE THREAD

**Issue by AndKe** [dddomodossola/PFD#12]
![Screenshot from 2021-03-21 09-26-43](https://user-images.githubusercontent.com/1468842/111900773-aec4d600-8a34-11eb-9afc-ccb7bcc9c1d1.png)

Please place a text area above the speed ladder.  (the yellow box is just to visualize the requested area, no yellow box is required)
the name could be simply "g"  -will be used to display groundspeed.

Thank you.

**Comment by dddomodossola** [comment]
@AndKe In order to add the ground speed field in that specific positin I had to divide the pfd elements. I have done this in a separate branch named "pfd_elements_splitted". Please take a look and tell me if you like it."

**Comment by AndKe** [comment]
Thank you, it looks good, but unfortunately, the Google Glass un unable to keep up with It at an update interval of 0.3 (where the previous version work well)
Is streaming the whole thing as a video-stream a very far-fetched idea?

**Comment by AndKe** [comment]
Let me delay the decision on this.
Can this solution be easily combined with the pyvisa appoach?  - or will we end up with two .svg's to be recompressed?/transmitted? - possibly creating additional overhead - or maybe even improve the performance due to fewer pixels :)
I have recently captured lots of .svg's as they are created before pyvisa recompresa them scriped something that can run simulated performance tests on Rpi4 - finding a sweet spot between compression level and size.

**Comment by AndKe** [comment]
Seeing that the pyvisa method works well, maybe the best method is not to split the svg, but rather add the text to the main .svg

**Comment by AndKe** [comment]
@dddomodossola Seeing that the pyvisa method works well, maybe the best solution is not to split the svg, but rather make the text files a part of the main .svg

**Comment by dddomodossola** [comment]
@AndKe Putting it in svg would cause a different look respect to the other text elements. Are you sure you want the ground speed in that exact position? Maybe it is possible to stack it between the text elements on the left?

**Comment by AndKe** [comment]
@dddomodossola 
You are right, I could sneak in another text filed between "left2" and "left3" and right-align it - especially with the "reduce black area"  change https://github.com/dddomodossola/PFD/issues/20#issuecomment-821888940
It could be nice. 
I am closing this issue.
