### ISSUE TITLE
please allow access to skid/slip indicator

### ISSUE THREAD

**Issue by AndKe** [dddomodossola/PFD#14]
ssd (skid/slip indicator) is the lower rectangular part under the red triangle.
Can I have a variable that can offset it to left/right by a number of pixels/percent (whichever is more convenient for you)

![Screenshot from 2021-03-30 16-38-24](https://user-images.githubusercontent.com/1468842/113007437-821c6700-9176-11eb-89f3-091ac7b38969.png)

**Comment by dddomodossola** [comment]
@AndKe Please indicate me the typical min/max values for this indicator and the respective min max positions. I will create a function to set this value and properly place the indicator.

**Comment by AndKe** [comment]
I am not actually sure yet which telemetry I would use to feed it :)  - the Y axis acceleration, or the side-slip data (also affected by wind)  - so I do not know the range yet.

The data is just relative, never exactly quantified for the pilot. 

you can make it go from -100 to +100 or any symmetrical range you choose.  maybe pixels or percent is easiest for you.
I will most likely need to scale the data anyway in the other thread.

The current state would be "zero" (triangle and rectangle placed as they are today)

Visually: please make it so that -100(or the number you choose) looks like:
![skidslip](https://user-images.githubusercontent.com/1468842/113493375-09533d00-94df-11eb-9500-f25052bd3361.png)

The black fill is just a suggestion to make it more visible.

**Comment by dddomodossola** [comment]
@AndKe I created a new method for this ;-) . Please try it

**Comment by AndKe** [comment]
Thank you, it works perfectly. Of course, my idea of solid black bar was not esthetically good, but now I know where to change it :)
