### ISSUE TITLE
Please point me to where to attach a <script> to be executed on load.

### ISSUE THREAD

**Issue by AndKe** [dddomodossola/PFD#16]
The google glass always load pages in a zoomed-in view, requiring to do two-finger gesture-based zooming and centering - a minor inconvenience to do precisely.

I have verified that this works on glass:  - where can I insert it so that it is executed once, only on page loading, not updates?

```
<script type="text/javascript">
if (screen.width == 427 && screen.height == 240) 
        {document.body.style.zoom="100%"}
</script>
```

I think of detecting it based on it's odd screen-size or browser size, both reported as (427x240) - much lower than its native resolution.

The user-agent is below, In case you think my suggestion is very dirty, and would like to suggest a "proper" way of doing that.

```
Mozilla/5.0 (Linux; Android 4.4.2; Glass 1 Build/XRH35; XE24;
5585826; user; release-keys;
e5d141d3c641 1988345942 734647bda7)
AppleWebkit/537.36 (KHTML, like Gecko) Version/4.0
Chrome/30.0.0.0 Mobile Safari/537.36

```

**Comment by dddomodossola** [comment]
@AndKe Done ;-)

**Comment by AndKe** [comment]
Thank you :)
