### ISSUE TITLE
Two minor code issues:

### ISSUE THREAD

**Issue by AndKe** [dddomodossola/PFD#18]
```  with self.update_lock:  ```  - I don't see it being used anywhere.  (maybe it works in a way I don't understand)

```  super(MyApp, self).on_close()  ```  there is no MyApp

**Comment by dddomodossola** [comment]
`with self.update_lock` creates a safe context where to access widgets preventing concurrent changes with the remi thread.
`super(MyApp, self).on_close()` can be removed ;-)
