### ISSUE TITLE
Vertical scale items fixed at 10?

### ISSUE THREAD

**Issue by AndKe** [dddomodossola/PFD#19]
```
class TapeVertical(gui.SvgGroup):
    value = 0
    scale_length = 1000
    scale_length_visible = 100
```

My understanding is that setting   scale_length_visible = 50 would show only five , instead of 10 values of speed/altitude.
Changing this value produces no visible effect.

**Comment by dddomodossola** [comment]
In that piece of code the class members are just declared and initializated. But in the class constructor the values are updated.
You should change this value where this class gets instanciated. For example here: https://github.com/dddomodossola/PFD/blob/342ea8d6f8a01146c6c716aecbfd4024b4fe1bc1/PFD.py#L598
