### ISSUE TITLE
Delay / overload or race condition causing trouble

### ISSUE THREAD

**Issue by AndKe** [dddomodossola/PFD#2]
In basic_svg_example, I did 'config_multiple_instance': False in order to be able to do rapid changes from desktop computer, to glass.
I can confirm that rapid changes/many changes are just fine and smooth.

I am using a "Performance MX" mouse, so I can spin the mouse scrollwheel and produce >10pulses per second.
The telemetry is updated at about 10hz-30hz (that I can limit)
In PFD.py  I changed the SpinbBox step size to 0.1    Giving the mouse-wheel speed, displays a neat, smooth animation of the pitch/yaw.

Google glass experience:
The page loads fine and fast, if I apply changes at a slower rate, 2hz or so, then all is fine and as smooth as it can be at 2Hz.
Any pitch/roll change seems quick, no sluggish drawing or anything like that.

Once I increase the speed of updates to maybe 5hz and beyond this can be observed:
-The webpage is lagging severely behind, 5-10 seconds after few faster scrolls.
-the webpage (on the glass) will not become responsive again after an idle period
-after 5 seconds, it may suddenly update, once, (fast) - then appear to be frozen again.
-this update is never partial.

I am not familiar with how Remi works when it comes to transmitting the data.
I had some long strings with fast millisecond updates sent to glass, working just fine, with a high rate of updates.
how many "updates" are rendered/transmitted during "no change" time?
Is there maybe some race condition when more updates are transmitted before they can be displayed?

For this application there is no need to send updates at higher rate than the incoming data changes, and the rate can very well be limited -especially for lower end systems like glass (but - as I understand it.. it's not much processing inside the glasses?)

**Comment by AndKe** [comment]
Correction: given enough time it will be responsive again after such "overload"

**Comment by AndKe** [comment]
The https://github.com/dddomodossola/PFD/commit/fd9748faf5b93d2757ee990152a82d6c34815a2e 
Seems to fix the issue, and cause another.
On glass: I see no positive pitch numbers.
And the ladder disappear on negative pitch both on glass and desktop browser.
But it does handle very fast changes just fine.
Maybe the text is a very intensive thing too - or can the SvgLine be the problem, so reducing width would help - what do you suggest ?

**Comment by dddomodossola** [comment]
@AndKe  Should be fixed with the latest version, please try it and if ok close this issue ;-)

**Comment by AndKe** [comment]
I will do later today (the google glasses are at home, I am at work)
BTW: all the past days were all based on the latest release of Remi - please remember to tell me to use master, if you do any relevant changes there.

**Comment by dddomodossola** [comment]
Ok, however I mean that I made changes to this project, not to remi

**Comment by AndKe** [comment]
Yes, works great ! -can't cause huge delays anymore.
