### ISSUE TITLE
Please optimize the pyvips version.

### ISSUE THREAD

**Issue by AndKe** [dddomodossola/PFD#20]
![Screenshot from 2021-04-17 20-32-34](https://user-images.githubusercontent.com/1468842/115126444-58b16700-9fcf-11eb-942f-336943881e2d.png)

1: Please shrink the graphical element resolution so that it only includes the used area. (the left, and right areas are better off not being included in the .png.) I would suggest that the .png contained the are within the yellow lines.
2: please enlarge vertically the graphical area, (the pyvips version does not use fill the area beneath it.)

**Comment by dddomodossola** [comment]
@AndKe I will do it soon ;-)
I understand that I have to enalrge the image, but I'm not sure to jnderstand the point 1

**Comment by AndKe** [comment]
Thank you.
Please let me explain "1":
currently: the part within the dashed yellow lines is a graphical element that is compressed to png and transferred:
![Screenshot from 2021-04-17 23-12-57](https://user-images.githubusercontent.com/1468842/115126894-c0b57c80-9fd2-11eb-817b-6fc62f10bff7.png)

it would be more efficient to transfer a smaller area like within these dashed lines:
![Screenshot from 2021-04-17 23-13-59](https://user-images.githubusercontent.com/1468842/115126913-e04ca500-9fd2-11eb-86a1-1bd32a01f73f.png)

Also, this would allow wider text-fields to the left.

**Comment by dddomodossola** [comment]
That's right, thank you for explaining

**Comment by dddomodossola** [comment]
@AndKe done ;-)

**Comment by AndKe** [comment]
The svg area is reduced horizontally by the area of the checker-board parts.
![Screenshot from 2021-04-24 10-58-24](https://user-images.githubusercontent.com/1468842/115960461-e29e8a00-a511-11eb-88fe-2df9bd72bf33.png)
I discovered this when I were about to run new performance tests.
Is there a particular reason you did not reduce it more?
I am just hoping to reduce possible bitmap operations, reducing transfer and decompression of the PNG. (I assume a svg is less affected by "unused" areas)

**Comment by AndKe** [comment]
@dddomodossola  in my quest for performance improvement, I did an awful hack in the line https://github.com/dddomodossola/PFD/blob/6894dbbe3a7e5454390272062fced3ab9350e9a8/PFD.py#L829

Changing it to ```elf.pfd.set_image_size((640.0-_w_margin-120)```  - I produced much narrower svg's (with the VSI partially chopped off because I did not figure out how to prevent that)  
it looked like (before/after):
![Screenshot from 2021-04-24 22-29-24](https://user-images.githubusercontent.com/1468842/115972229-5e69f800-a54d-11eb-90f6-ae3f957077be.png)

I did some performance data on recompressing this in RPi4 at 2Ghz.
(see the second sheet)  https://docs.google.com/spreadsheets/d/1KEKihgpQQueVZyYXqa2E5gElZUcFMm2NYtlELlhI9-Y/edit?usp=sharing

So there is a reduced data amount during transmission to the glass, not much in terms of compression performance on the RPi  (each frame still takes about 0.21s)

And then there is the CPU load on the glasses at  update_interval=0.25:
current performance version:     29% CPU 
modified performance version:  27% CPU  (not much better)

Maybe the biggest advantage of removing the left black area, is that a groundspeed cab be placed directly to the left of the red airspeed box.

**Comment by dddomodossola** [comment]
@AndKe The image is already reduced. I see the image like this:
![image](https://user-images.githubusercontent.com/341675/116616151-9e115500-a93c-11eb-9f39-ac65603bce36.png)
If you see a different image size, please check the git branch on which you are working. I'm working on branch **cutting_edge_performance**.

**Comment by AndKe** [comment]
Yes, I know you reduced it - I were nagging about the black area in yellow, which besides minimal performance improvements in my tests - would allow for a groundspeed text to be placed nearby the airspeed (I could add text where the orange box is)

As you see above, my attempts to reduce the black area ate the VSI,  - you do not need to spend more time on that,  I imagine it is not trivial and you had a reason to left the black part in.

**Comment by dddomodossola** [comment]
I did not reduced it more because, given the attitude indicator at the center (I coded it this way at the beginning), I sized the right part to the minimum size to contains indicators. The left side has to be identical to the right ( because attitude indicator is the center).
However the image is smaller than you indicated above. There is only a tiny black part on the left.

**Comment by AndKe** [comment]
@dddomodossola I agree and understand, this is why I had no success shrinking the area myself. Thank you.
