### ISSUE TITLE
does .settext support line change?

### ISSUE THREAD

**Issue by AndKe** [dddomodossola/PFD#23]
I am trying to add line change to text.
self.left1.set_text("GS" + str(gs) + "/n new line")

I've tried <br> , &#10;&#13;   /n .. but nothing override the autowarp.
Is there a way of adding a line-change ? 

Is issue is of very low importance :)

**Comment by dddomodossola** [comment]
Hello @AndKe ,

The newline character is "\n", instead of "/n". However, in order to preserve newlines, you should set the following style to the widget:

    mytxtwidget.css_white_space = "pre"

Kind Regards ;-)

**Comment by AndKe** [comment]
Thank you ! :)
