### ISSUE TITLE
Some pitch ladder observations:

### ISSUE THREAD

**Issue by AndKe** [dddomodossola/PFD#3]
In Chrome/Firefox a positive pitch looks like 
![Screenshot from 2021-01-26 19-05-24](https://user-images.githubusercontent.com/1468842/105885530-89ee4c80-6009-11eb-864c-f6e295d45016.png)
 and a negative reoll over to 
![Screenshot from 2021-01-26 19-05-53](https://user-images.githubusercontent.com/1468842/105885563-95da0e80-6009-11eb-9b4d-18d98c421b29.png)
: 

On google glass.. the pitch is 190° at the 0° position, so 10° positive pitch in crime is somehow 200° on google glass.
Any negative pitch (tested -1... -150)

**Comment by dddomodossola** [comment]
@AndKe 
Can you please test the latest version? However I'm not sure to understand. Do you mean that the values shown on Chrome/Firefox are shown differently on glasses (with an 'offset' of 190°) ?
Please let me know with the latest version.

**Comment by AndKe** [comment]
Please see a better explanation of the issues with previous version, and a test of current version in the video  
https://drive.google.com/file/d/1NC1ONBOp5qaWTiejazyUoCoNbatbxhSW/view?usp=sharing
- downloading the video may result in better playback quality. 
- the "previous version" is still here: https://github.com/ArduPilot/pymavlink/blob/master/tools/mavflighttime.py (a bit tweaked from the original version, with fewer pitch ladder lines and different angles.)
- 
Please note the aliasing effect with 0.x degree roll on firefox in the final seconds of the video.
This effect is completely gone in today's PFD.py 

Firefox is not a priority if you know it to be buggy - I report it partially just in case you would like to know.
Another odd thing to observe is that the spinboxes do not align properly on glass browser running today's version.

The current version looks really good.

**Comment by dddomodossola** [comment]
Hello @AndKe , can you please test the latest version? I made changes to fix the missing text on google glasses. Please let me know if the values are visible.

**Comment by AndKe** [comment]
@dddomodossola 
To my surprise, the Firefox distortion seen in the previous video is gone.
On the Glass, there are letters now, capable of rotation, but it's hard for me to understand how the result can be that different - so I have made a video for you to see: https://drive.google.com/file/d/1lPhP6crMjizB5EWujNlZUdynRjA-o7EJ/view?usp=sharing

**Comment by AndKe** [comment]
@dddomodossola  Additional information (please note my previous reply)
If the circular compass is troublesome, feel free to use this PFD as an example of "horizontal speed-tape style compass:"
https://pmflight.co.uk/a320-primary-flight-display/

The "tape" behaves as a circular loop, displaying "34  35 0 01 02 03 ..." in the example you can see 13(130°)  14(140°) and so on . 
The violet number "093" is a bug defined by flight director computer /(next waypoint or such)  this is also indicated by the violet "<" sign near the four "o"'s above the compass.  the "<" is displayed only when the "093" is out side of it's proper position in the tape.   If the bug was set to "125" , then there would not be a "<" on the edge.

Some PFD's may have a compass like this, but with full course above center of the compass tape (mockup below showing 139°)
. 
![Screenshot from 2021-01-31 14-23-35](https://user-images.githubusercontent.com/1468842/106385388-6728b300-63d0-11eb-9b35-228d542aac90.png)

I guess this style may be much easier to implement, and even use less space.
It is also usual to combine the indicator with the four cardinal directions like:    **N** 01 02 03 ...  07 08 **E** 09 10 11 ... 16 17 **S** 19 20...

**Comment by dddomodossola** [comment]
@AndKe should I display the "The violet number "093" is a bug defined by flight director computer" field?

**Comment by dddomodossola** [comment]
@AndKe Please try the latest version, I implemented the stripe style orientation indicator ;-)

**Comment by AndKe** [comment]
I will try at home later today (in about 7 hrs)
Target bearing/"the bug"  is not very important yet, should you feel it's trivial then please do - in that case, a variable (integer between 0-359) should define where that point is   
Both 0 and 360 it the same (north) and if set to "999" or "-1"  - then the feature is disabled.

**Comment by dddomodossola** [comment]
@AndKe It should be easy to do. But, does it stays fixed in that position, or it moves with the scale?

**Comment by AndKe** [comment]
It is "fixed" to, and moving with the tape as long the bug's indicated position is on the visible part of the tape, otherwise, (when the target position is not visible it is "stuck" to a side until position is visible:
The logic is: if target heading is visible on tape, place bug on the correct place.
If the target is outside the visible range : draw it on the shortest way to target, stick to the side of tape, and indicate shortest way.

If flying 0° (north)  and the bug is set to 181°  - then the bug would be on the right side saying " 181" or ">181")
if the pilot turn to the left, heading 20°  - then the bug would jump to the left side of the compass-tape, indicating that continuing left is the closest way to target heading.
![20210202_123237](https://user-images.githubusercontent.com/1468842/106595444-e1ce0b80-6553-11eb-8168-cb314c4ee4bd.jpg)

**Comment by dddomodossola** [comment]
@AndKe Ok, great explanation, I understand

**Comment by AndKe** [comment]
@dddomodossola It looks great.
As "always", there are some odd things on the glass, the vertical spacing... but not critical.
Watching it in Glass, the main heading (big zero) should be a bit smaller..  and you can simplify the line by displaying every-second direction, and skip the 45° directions so
E 10 11 12 13 SE 14 15 16 17 S
would be displayed as
E  10  12  14   16   S  29  22  24
or..  maybe keeping the intercardinal directions like:
E    10    12    SE    14    16   S
Both suggestions make occupy a little less space and prevent letters of the intercardinal direction to mix with the numbers.
![Screenshot from 2021-02-02 14-57-13](https://user-images.githubusercontent.com/1468842/106612344-50699400-6569-11eb-80d5-a257f7418c53.png)

**Comment by dddomodossola** [comment]
Ok thank you for your comments. Pushed some changes, you can check ;-)

**Comment by AndKe** [comment]
*Very* nice ! - what a nice surprise with the speed/altitude ladder :)
Please increase the numbers along the speed/alt ladder to the size of the pitch/roll indicator.
Please move the speed/alt ladders closer to the attitude indicator, the black background works well. 

Allowing space for three digit speed and four digit altitude is fine, as slower aircraft tend to use m/s speed, faster use knots, and few RPAS go over 9999ft/m

**Comment by AndKe** [comment]
Please note that the Speed/Altitude numbers may very well overlay a part of the respective tape.
The main objective of having moving tape/animated numbers (not sure the plant thing is do-able here) is to provide instant information on how fast, and which way the speed/altitude is changing  - please see https://youtu.be/hjrELZXYUNQ?t=1246

**Comment by dddomodossola** [comment]
> Please note that the Speed/Altitude numbers may very well overlay a part of the respective tape.
> The main objective of having moving tape/animated numbers (not sure the plant thing is do-able here) is to provide instant information on how fast, and which way the speed/altitude is changing - please see https://youtu.be/hjrELZXYUNQ?t=1246

I'm not sure to understand. Do you mean that it is required to have the actual value with animated scrolling numbers?

**Comment by AndKe** [comment]
No, animation of the numbers is not required - I guessed that it alone was a lot of work.
For an equally nice impression of the trend, I asked for a scale of the speed/elevation tape that could be set by variable.
This way, I can fine-tune the variable so that the speed/elevation tape moves at a rate that produces a nice animation.

Right now, we seem to have good space on the sides of the PFD when rendered in the native resolution.
I hope to change the request for the final text fields (less complex items) from a messy layout suggestion before: 
![unnamed](https://user-images.githubusercontent.com/1468842/106780051-e673ec00-6647-11eb-81db-e222257884e6.jpeg)

...more to a line on the bottom, and 3-4 fields on each side of the PFD.

What I meant by:
"Please note that the Speed/Altitude numbers may very well overlay a part of the respective tape."
was something like:
![Screenshot from 2021-02-03 17-29-53-2](https://user-images.githubusercontent.com/1468842/106780301-21761f80-6648-11eb-8f93-25d83ac4e7ac.png)

Some horizontal space is saved.
Also, please note that the slip/slide and compass pointer is red, then the other "actual numbers" pointers should be too.
The Pink color may be reserved for bugs (like a set course, altitude, or speed. )

As for the graphics/esthetic part, I am pretty useless, so please use a design you like :)

**Comment by dddomodossola** [comment]
Hello André, some of the points you mentioned here are already done:
- Actual altitude/speed value indicators are ok;
- Pink indicators are now red;
- Altitude/speed indicators accepts scale values.

Can you please redraw the image with additional fields on the actual image? 
![image](https://user-images.githubusercontent.com/341675/110234512-34239300-7f2b-11eb-9160-0cee97430b0a.png)

I found it difficult to understand where to put objects, because, in example "TEXT 0" would overlap the orientation indicator in the actual position.

**Comment by AndKe** [comment]
You are right. - The "Text0" was a place planned for placing a flight mode, string.  (not demanding high readability, but now conflicting with the compass )

Please see the new mockup - from now on, I do not reference any of the old text fields or mockups, only this:
![pfd-mockup](https://user-images.githubusercontent.com/1468842/110237023-d5194a80-7f39-11eb-971b-d1426228ca42.png)

A major design target should be to effectively use the native resolution of the glass (640×360)

Legend:
- The blue frame : possible guesstimated 640x360 area
- Green lines: lightly visible field dividers, (maybe grey or other suitable color (or maybe none - maybe we should just skip them ?))
- Red thingy: VSI (vertical speed indicator)
- I do not have a strong opinion about the placement of VSI, it could be to the left of the altitude tape. or even overlaying the right part of the artificial horizon
- Please note that there is some "wasted" space to the right of the VSI. - one could move the AHI, and speed/altitude tapes to the right, and make fields 1,2,3,4 wider.
- T0 , T1 , wide text fields
- S(status field)  may display strings like "Fix3 HDOP: 0.7"      
- M (ode fiels)  may display strings like "STABILIZED"  
- 5 ,6, just some strings...
- 1,2,3,4    may display strings like : "Gen: 25.5v"   "Batt:  23.2V"    and so , maybe automatic line wrap is useful, maybe one just need one line ... (I am open to suggestions - as I do not know what features exist)
- In the same way, If easily possible, it would be very useful if some variable could change the font color, background color, or blink a string (in order to attract attention, given critical information)   - that is... of course, if it is rather simple for you to add such aattribute.

**Comment by dddomodossola** [comment]
Hello @AndKe , please review the actual changes ;-)

**Comment by AndKe** [comment]
Wow !
I am totally in awe of the way you used self.main_container.set_from_asciiart  - you truly know the best ways to do things :)
what a nice way to nail the resolution and distribution of items spot on!

1: I have never seen VSI in such a design, but why not :) please note than VSI usually moves between two fixed points, like +10 ..-10 is ok, and if it's the same to you, it would be nice if the +10 ..0....-10 markings were stationary and the bug moved up and down along that area.  

2: I have no knowledge of the processing power spent on rendering/updating such VSI vs a simple line/geometric object. (I mean CPU of the glass)  - could you please enlighten me on how things are updated, and what kind of updates cost more CPU load, than others ? - or is there a rule for what "costs" ? 
is complexity of the view,  the resolution , item count / dynamic or static item count affecting the CPU the most?   

3: the resolution is spot on when the line ```self.main_container.append(gui.Label('right'), "right")```  is commented out, I do not see any drawbacks of commenting it out.

**Comment by dddomodossola** [comment]
@AndKe I provided you some information about remi rendering and update processing in the issue #8 . Yes I can make VSI with a simple line and a pointer. It will be ligther, but only a very little.

**Comment by AndKe** [comment]
Yes please, such a line-based VSI is mainly more "traditional" and "instantly recognizable".
There is a little optic distortion near the vertical edges of the glass.  - please add a slight "margin" on the left/right
(The margin width could be the width of "TES" in "TESTING" is fine)
Or: maybe simpler: please make the "left1,2,3,4 and s" appear as centered - this way there will be a "natural" margin on the left.

I think that the VSI, once replaced by a polygon, is placed well (reading the numbers is more affected by the slight optical distortion, than a symbol/line.)

Please make the numeric compass heading update (marked with red)
![Screenshot from 2021-03-14 10-00-53](https://user-images.githubusercontent.com/1468842/111063180-7e69be80-84ad-11eb-8b7e-6d8b8a5c5bb7.png)

**Comment by AndKe** [comment]
in regard to the above-mentioned margin, I've found that this produces a nice result:
```
        | left1        | pfd                                                                                     |
        |    |left2    | pfd                                                                                     |
        |    |left2    | pfd                                                                                     |
        | left2        | pfd   
```
Is that an acceptable/correct way of moving the text around?

**Comment by dddomodossola** [comment]
@AndKe Left margin done

**Comment by dddomodossola** [comment]
@AndKe Simple VSI done, Heading update done. ;-)

**Comment by AndKe** [comment]
Fantastic progress :)
I will soon start to implement real data.

The next focus could be to implement the speed tape coloring /settings:
I made it a bit translucent, and placed as I did .. you may adjust the placement as you see fit/practical.

This would work based on five velocity variables:
White tape in the example:
Vso=12 (stall speed flaps out) - defines the start of the white tape on the speedtape
Vfe=40 (maximum flaps extended speed) -defines maximum allowed fully extended flap speed, end of white tape
(Vfe will always be > Vso)

Green Tape: 
Vs=25 (clean configuration stall speed) -shows normal operation range start
Vne=68 (never exceed)  - marks the upper end of green tape 
(Vne will always be > Vs)

Red Tape:
Any speed > Vne is marked with red background.

Vspace=10    indicate that the space between numbers is "10"  (as in the example)  10,20,30...
If Vspace = 5   then the ladder should scale as 5,10,15,....

![Screenshot from 2021-03-14 21-09-09](https://user-images.githubusercontent.com/1468842/111083234-c3710d80-850c-11eb-91f9-76af3e93f750.png)


Finally. If not too complex, please make the speed ladder skip numbering "negative" speeds:
like:  (example to the right is better, if not too complex.)
![Screenshot from 2021-03-14 21-35-52](https://user-images.githubusercontent.com/1468842/111083426-de904d00-850d-11eb-8d29-630fff506ae4.png)

**Comment by dddomodossola** [comment]
@AndKe Done, please check this
