### ISSUE TITLE
Bank angle change.

### ISSUE THREAD

**Issue by AndKe** [dddomodossola/PFD#6]
Can you please change the way the bank angle and slip/slide indicator works?
I think/hope this change will mainly reuse the code you already made.

The part in yellow (the angle scale) should be stationary
And the slip/slide indicator  (marked in green) should rotate along the stationary angle scale. and disappear over 90° , or be controlled by some "enable" logic (described below)

![Screenshot from 2021-02-02 21-29-37](https://user-images.githubusercontent.com/1468842/106659147-9db42880-659e-11eb-9316-f6faf55ac8fe.png)

The main reason I ask for this is that the PFD looks oddly when banked 90° or more, or inverted.

If changing it is time-consuming, (or regardless of that) please consider adding a "enable" variable to different non-critical indicators.

In aviation, in the case of extreme bank/pitch angles, many manufacturers remove information to make the human better focus on 
critical issues like attitude/speed, simply to aid in faster and more correct response - instead of, for example, displaying an inverted roll indicator. 
If you choose to, you may make some "enable" variables for the roll scale,  the slip/skid indicator/ compass. (I would then toggle them based on the state)

**Comment by dddomodossola** [comment]
@AndKe This is done, please check and eventually close issue ;-)

**Comment by AndKe** [comment]
@dddomodossola Perfect ! - and the >90° hiding is once too.
