### ISSUE TITLE
Some way to mark PFD as INOP

### ISSUE THREAD

**Issue by AndKe** [dddomodossola/PFD#9]
In case the telemetry stream stops or have lots of dropped packets, I need to detect that, and make it somehow visible that the data is not current/valid.  

It could be as simple as having a variable that could set the color of the (normally black) background to something else (I would set it to red, then maybe even alternate it)

**Comment by dddomodossola** [comment]
@AndKe Done, please let me know if this is ok

**Comment by AndKe** [comment]
This is plenty fine, thank you, please expose it as a variable (unless it's obvious)  I just had to test this, will be back later..
